<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Apis.Core" Version="1.75.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Cookies" Version="2.3.11" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Features" Version="5.0.17" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="8.0.1" />
    <PackageReference Include="StackExchange.Redis" Version="3.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\IMS.DAL\IMS.DAL.csproj" />
    <ProjectReference Include="..\IMS.Models\IMS.Models.csproj" />
  </ItemGroup>

</Project>
